// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazarVeAlintilari.Data;

#nullable disable

namespace YazarVeAlintilari.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230814180828_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YazarVeAlintilari.Data.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Soz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yazars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Soz = "Başarmak için ilk adım atmalısınız.",
                            YazarAdi = "Zig Ziglar"
                        },
                        new
                        {
                            Id = 2,
                            Soz = "Sadece bugünü değil, yarını da düşünerek hareket edin.",
                            YazarAdi = "Albert Einstein"
                        },
                        new
                        {
                            Id = 3,
                            Soz = "Başkalarının sınırlamaları sizi durduramaz, yeter ki inanın.",
                            YazarAdi = "Roy T. Bennett"
                        },
                        new
                        {
                            Id = 4,
                            Soz = "Başarı, en çok denemekten korkmayanların elindedir.",
                            YazarAdi = "Robert Kiyosaki"
                        },
                        new
                        {
                            Id = 5,
                            Soz = "Her adım, hedefe bir adım daha yaklaşmaktır.",
                            YazarAdi = "Confucius"
                        },
                        new
                        {
                            Id = 6,
                            Soz = "Engeller sadece hedefe giden yolda ki yönlendirmelerdir.",
                            YazarAdi = "Barbara Sher"
                        },
                        new
                        {
                            Id = 7,
                            Soz = "Zorluklar, gerçek potansiyelinizi ortaya çıkarmak için fırsatlardır.",
                            YazarAdi = "Malcolm X"
                        },
                        new
                        {
                            Id = 8,
                            Soz = "Başkalarının başarısızlıklarından değil, kendi azminizden etkilenin.",
                            YazarAdi = "Denis Waitley"
                        },
                        new
                        {
                            Id = 9,
                            Soz = "Başlamak için mükemmel bir zaman yoktur, zamanı kendiniz yaratırsınız.",
                            YazarAdi = "George Bernard Shaw"
                        },
                        new
                        {
                            Id = 10,
                            Soz = "Hayal ettiğiniz yaşamı yaşamak için şimdi adım atın.",
                            YazarAdi = "Sinan Taşyapar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
